# Сделано онли для того чтобы не париться запускать бдшки

name: diplom
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diplom
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  redis:
