import { Product } from '@/types/catalog';

export const categories = [
  'Комбинезоны',
  'Куртки',
  'Брюки',
  'Футболки',
  'Платья',
];

export const sizes = [
  '50',
  '56',
  '62',
  '68',
  '74',
  '80',
  '86',
  '92',
  '98',
  '104',
  '110',
  '116',
  '122',
  '128',
  '134',
  '140',
  '146',
  '152',
  '158',
  '164',
  '170',
  '176',
  '182',
  '188',
  '194',
  '200',
];

export const colors = ['Синий', 'Красный', 'Зеленый', 'Желтый', 'Черный'];

export const materials = ['Хлопок', 'Шерсть', 'Синтетика', 'Джинс'];

export const seasons = ['Лето', 'Зима', 'Демисезон'];

export const genders = ['Мальчик', 'Девочка', 'Унисекс'];

export const countries = ['Россия', 'Турция', 'Китай', 'Польша'];

export const mockProducts: Product[] = [
  {
    id: 1,
    title: 'Детский комбинезон Зимний',
    image: 'https://via.placeholder.com/300x400?text=Комбинезон1',
    price: 3500,
    category: 'Комбинезоны',
    size: ['86', '92', '98'],
    color: 'Синий',
    material: 'Синтетика',
    season: 'Зима',
    rating: 4.5,
    gender: 'Унисекс',
    country: 'Россия',
  },
  {
    id: 2,
    title: 'Куртка демисезонная',
    image: 'https://via.placeholder.com/300x400?text=Куртка1',
    price: 2800,
    category: 'Куртки',
    size: ['74', '80', '86'],
    color: 'Красный',
    material: 'Хлопок',
    season: 'Демисезон',
    rating: 3.8,
    gender: 'Девочка',
    country: 'Турция',
  },
  {
    id: 3,
    title: 'Брюки для мальчика',
    image: 'https://via.placeholder.com/300x400?text=Брюки1',
    price: 1500,
    category: 'Брюки',
    size: ['98', '104', '110'],
    color: 'Зеленый',
    material: 'Джинс',
    season: 'Лето',
    rating: 4.0,
    gender: 'Мальчик',
    country: 'Китай',
  },
  {
    id: 4,
    title: 'Футболка с принтом',
    image: 'https://via.placeholder.com/300x400?text=Футболка1',
    price: 800,
    category: 'Футболки',
    size: ['80', '86', '92'],
    color: 'Желтый',
    material: 'Хлопок',
    season: 'Лето',
    rating: 4.7,
    gender: 'Унисекс',
    country: 'Россия',
  },
  {
    id: 5,
    title: 'Платье летнее',
    image: 'https://via.placeholder.com/300x400?text=Платье1',
    price: 2200,
    category: 'Платья',
    size: ['86', '92', '98'],
    color: 'Синий',
    material: 'Хлопок',
    season: 'Лето',
    rating: 4.2,
    gender: 'Девочка',
    country: 'Польша',
  },
  {
    id: 6,
    title: 'Зимний комбинезон Плюшевый',
    image: 'https://via.placeholder.com/300x400?text=Комбинезон2',
    price: 4500,
    category: 'Комбинезоны',
    size: ['92', '98', '104'],
    color: 'Черный',
    material: 'Синтетика',
    season: 'Зима',
    rating: 4.8,
    gender: 'Унисекс',
    country: 'Россия',
  },
  {
    id: 7,
    title: 'Демисезонная куртка Стильная',
    image: 'https://via.placeholder.com/300x400?text=Куртка2',
    price: 3200,
    category: 'Куртки',
    size: ['104', '110', '116'],
    color: 'Красный',
    material: 'Шерсть',
    season: 'Демисезон',
    rating: 4.0,
    gender: 'Мальчик',
    country: 'Турция',
  },
  {
    id: 8,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 9,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 10,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 3.5,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 5.0,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 5.0,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 5.0,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 5.0,
    gender: 'Девочка',
    country: 'Китай',
  },
  {
    id: 11,
    title: 'Брюки для девочки',
    image: 'https://via.placeholder.com/300x400?text=Брюки2',
    price: 1800,
    category: 'Брюки',
    size: ['86', '92', '98'],
    color: 'Желтый',
    material: 'Джинс',
    season: 'Лето',
    rating: 5.0,
    gender: 'Девочка',
    country: 'Китай',
  },
];
